### ISSUE TITLE
can make a little change for output

### ISSUE THREAD

**Issue by thangckt** [eschnett/zotero-citationcounts#1]
Hello, 

Thank you so much for an awesome plugin.
I have a suggestion that whether you can make a little change for the format of output?
The current output is:  Citations (Crossref): 577 [2020-11-23]
Suggest to:  577 Citations (Crossref), [2020-11-23]

The reason is to more convenient to show the number of citations in the Extra column
Since it has a limitation in column width, so one will expect to show "557" rather than whole string

Thank you so much

**Comment by eschnett** [comment]
@thangckt Thanks for the suggestion. Please check out the new release 1.1.0 where I implemented this.
