### ISSUE TITLE
The plugin is incompatible with the latest beta release of Zotero

### ISSUE THREAD

**Issue by dualer** [eschnett/zotero-citationcounts#17]
See [this](https://github.com/ethanwillis/zotero-scihub/issues/67)

**Comment by ArronQiu** [comment]
According to the issue mentioned by @dualer, I tried the following and surprisingly found it work:
1. open '.xpi' by a zip software.
2. open 'install.rdf' by a text software.
3. change the minVersion and maxVersion like this:
```
<em:minVersion>5.0.79</em:minVersion>
<em:maxVersion>6.0.*</em:maxVersion>
```
4. save, close, and now you can install and find it compatible.

**Comment by dualer** [comment]
@ArronQiu I have tried your method, but I got the following error report: 
```
The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.
```
Do you know what went wrong?

**Comment by lshowo** [comment]
> @ArronQiu I have tried your method, but I got the following error report:
> 
> ```
> The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.
> ```
> 
> Do you know what went wrong?

me too

**Comment by ArronQiu** [comment]
@dualer @lshowo Sorry that I don't know the exact reason, but the same issue has been raised [here](https://github.com/ethanwillis/zotero-scihub/issues/67) and solved. You may try following the instruction:
> If you want modify a xpi plugin:
> 1- unzip 'xpi' exactly as 'zip'.
> 2- edit file in text editor.
> 3- [Important] Select the files and folders at root level and zip from here. Do not zip from outside the plugin folder.
> 4- no need to modify suffix 'zip' to 'xpi', just drag it to zotero add-on manager.

Hope it work.

**Comment by dualer** [comment]
@ArronQiu Thanks. Problem solved.

**Comment by ArronQiu** [comment]
@dualer Please close the issue since the problem was solved.

**Comment by shyyelring** [comment]
thanks

**Comment by ArronQiu** [comment]
My pleasure to help :)

**Comment by XinwenLi-Econ** [comment]
> @dualer @lshowo Sorry that I don't know the exact reason, but the same issue has been raised [here](https://github.com/ethanwillis/zotero-scihub/issues/67) and solved. You may try following the instruction:
> 
> > If you want modify a xpi plugin:
> > 1- unzip 'xpi' exactly as 'zip'.
> > 2- edit file in text editor.
> > 3- [Important] Select the files and folders at root level and zip from here. Do not zip from outside the plugin folder.
> > 4- no need to modify suffix 'zip' to 'xpi', just drag it to zotero add-on manager.
> 
> Hope it work.

Thanks!

**Comment by adahfbch** [comment]
> @dualer @lshowo Sorry that I don't know the exact reason, but the same issue has been raised [here](https://github.com/ethanwillis/zotero-scihub/issues/67) and solved. You may try following the instruction:
> 
> > If you want modify a xpi plugin:
> > 1- unzip 'xpi' exactly as 'zip'.
> > 2- edit file in text editor.
> > 3- [Important] Select the files and folders at root level and zip from here. Do not zip from outside the plugin folder.
> > 4- no need to modify suffix 'zip' to 'xpi', just drag it to zotero add-on manager.
> 
> Hope it work.

Thanks, problem solved
