### ISSUE TITLE
Removal tool for the "Extra" field

### ISSUE THREAD

**Issue by thepero** [eschnett/zotero-citationcounts#2]
First of all, thank you very much for the great tool. A very useful addition to Zotero.

At the moment, when I get Semantic Scholar citation counts and subsequently Crossref citation counts for the same items, the Crossref counts are appended to the Semantic Scholar ones. It would be useful to erase the "Extra" field before getting counts from a different site or add a function that erases/removes "Extra" field entries of selected items/publications.

**Comment by eschnett** [comment]
I thought about this, but in the end there are people who want to see all citation counts (from all sources), so that one can report the highest one. I thus decided that the counts should have a unique prefix or suffix, and that they should not overwrite each other.

I see that your suggestion would be useful as well. Maybe there could be a toggle for your behaviour, or (as you suggest) an extra menu item to delete all citation counts from a particular source.

Do you have enough JavaScript experience to give this a try?

**Comment by thepero** [comment]
An extra menu item would be wonderful. Unfortunately, I don't have enough experience with JavaScript to do it (at least not in a timely and enough realiable manner).

**Comment by ABMalhotra** [comment]
In my opinion, the handling of contents of the Extra Field is beyond the scope of this add-on. If you are interested in clearing the extras field, there is a solution involving SQL query on your zotero database that I have used. Note that this is **extremely risky** as it can lead to corruption so make sure you make a copy of your database first. https://forums.zotero.org/discussion/12992/a-way-to-delete-all-info-from-all-extra-fields

**Comment by iphiphiph** [comment]
If this will not be implemented as a feature, there is another way of achieving what you want to do without having to tinker with SQL queries. Just go to Tools → Developer → Run JavaScript in Zotero and paste the JavaScript below and all Extra fields from all entries will be stripped. You can then run zotero-citationcounts to get an Extra column sortable by citations.

var fieldName = "extra";
var newValue = "";

var fieldID = Zotero.ItemFields.getID(fieldName);
var s = new Zotero.Search();
s.libraryID = ZoteroPane.getSelectedLibraryID();
var ids = await s.search();
if (!ids.length) {
return "No items found";
}
await Zotero.DB.executeTransaction(async function () {
for (let id of ids) {
let item = await Zotero.Items.getAsync(id);
let mappedFieldID = Zotero.ItemFields.getFieldIDFromTypeAndBase(item.itemTypeID, fieldName);
item.setField(mappedFieldID ? mappedFieldID : fieldID, newValue);
await item.save();
}
});
return ids.length + " item(s) updated";

**Comment by thepero** [comment]
Many thanks, it worked like a charm! This is a nice solution and does exactly what I wanted. I believe we can close the issue.

**Comment by OmidS** [comment]
I wanted to remove remnants of the old citation addons (things such as "ZSSC: 00000" or "00000") from the "extra" field but keep the rest of its content. So I built on the code form @iphiphiph to remove only those lines of the "extra" field that match citation-related patterns. Here is the code in case it is useful for others:
https://gist.github.com/OmidS/5bca086c9363a0f42dc0fe86c8ed6306
