### ISSUE TITLE
Not Getting Semantic Scholar Citations/ Documentation Request

### ISSUE THREAD

**Issue by alexanderosmith** [eschnett/zotero-citationcounts#23]
What metadata is/are necessary for this program to grab Semantic Scholar cites? In many cases, I look at Semantic Scholar, and see there are citations, however the add-on returns nothing.

Sorry I couldn't solve this myself. I tried digging through some of the documentation for Semantic Scholar's API, but it isn't terribly clear what I need or where to put things in Zotero to make sure I get a response.

For CrossRef, for example, it's pretty clear that all I need is an accurate DOI (because that's how CrossRef works). It would be super helpful if the necessary metadata for each of these citations existed somewhere and how to check them. Although I realize that might be a lot of documentation.

**Comment by adrien-perello** [comment]
Could it be because the document you are looking for does not have a field "DOI" (which is the case for example for books and book chapters - see the discussion #20 )

**Comment by alexanderosmith** [comment]
Thanks for the update. Sorry for the repeat post.
