### ISSUE TITLE
Ask don't work when highlighting text in PDF

### ISSUE THREAD

**Issue by pencilheart** [eschnett/zotero-citationcounts#28]
When highlighting text on Zotero PDF, this plugin works too. No need to do this.

**Comment by zzqxztc** [comment]
Yes, i also have this problem

**Comment by ChangQingAAS** [comment]
same

**Comment by jakobbaumgartner** [comment]
The bug is still here. When adding comments or highlights this pop up keeps showing up in bottom right corner of the Zotero program. It is distracting from work.

![image](https://user-images.githubusercontent.com/27065681/215450008-47311d2c-3044-45e3-bbe7-2d0937b9cb53.png)

**Comment by AlonOfficial** [comment]
same problem

**Comment by huangzy313** [comment]
Same problem :(

**Comment by Haulyn5** [comment]
same problem

**Comment by jasonmoy28** [comment]
Same problem

**Comment by yyNoBug** [comment]
Same problem :(
