### ISSUE TITLE
.xpi ignored?

### ISSUE THREAD

**Issue by EA-Williams** [eschnett/zotero-citationcounts#4]
I'm new to Zotero plug-ins and Git ignore files, but to my understanding the .xpi itself hasn't been uploaded onto Github because `*.xpi` is included in the `.gitignore`. Am I missing something?

**Comment by ABMalhotra** [comment]
Check the releases section of a repo. https://github.com/eschnett/zotero-citationcounts/releases

**Comment by eschnett** [comment]
The `*.xpi` file is autogenerated and is therefore not included in the git repository. The script `bin/build.sh` creates a new `*.xpi` file. When I release a new version, I manually upload the `*.xpi` file to Github as a release artifact.

If you are making changes yourself, then you would run the `bin/build.sh` script after each change to create a new `*.xpi` file. You then need to point Zotero (See `Tools` -> `Add Ons` -> Gear -> `Install Add-On From File...`) manually to this `*.xpi` file to reload the plugin.

**Comment by EA-Williams** [comment]
Thanks both, I just found it in the releases.
