### ISSUE TITLE
Archive incompatible with zotero version error 

### ISSUE THREAD

**Issue by zazim13** [eschnett/zotero-citationcounts#42]
Hi thank you for your work. 
I have noticed that this error occurs when I try to install this plug-in using the Source code (zip) : 
Error: The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

This error occurs even when I rename the .zip to .xpi. I think that the problem is the archive. What worked for me is to extract the source code from the .zip , then archive it again **but from inside the repo(I think the problem comes from this).** 

Thanks 
Hakim

**Comment by adrien-perello** [comment]
Check here: https://github.com/eschnett/zotero-citationcounts/issues/41#issuecomment-2304777072
it worked for me

**Comment by sascharo** [comment]
> Hi thank you for your work. I have noticed that this error occurs when I try to install this plug-in using the Source code (zip) : Error: The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.
> 
> This error occurs even when I rename the .zip to .xpi. I think that the problem is the archive. What worked for me is to extract the source code from the .zip , then archive it again **but from inside the repo(I think the problem comes from this).**
> 
> Thanks Hakim

This plugin is currently not compatible with the latest stable Zotero release.

**Comment by sascharo** [comment]
This one worked for me in version 7.0.4-beta: https://github.com/FrLars21/ZoteroCitationCountsManager/releases

**Comment by zazim13** [comment]
Thank you for your answers
