### ISSUE TITLE
Prepending rather than appending citation count to entries

### ISSUE THREAD

**Issue by teristam** [eschnett/zotero-citationcounts#6]
First of all, thank you so much for this wonderful plugin! It works wondefully and really help to prioritize the items in zotero.

I just have one small suggestion for improvement. Now the citation info is appended after the other entries in the Extra field, which make sorting using the citation count very difficult. It's because the Zotero Connector browser extension adds all kinds of junks to the Extra field. Is there a way to prepend the citation info before the other entires in the Extra field? I know we can use some javascript/SQL to do that but that's only for old items. You have to do it again when you add new items.

I don't know how hard it is to implement this, but this small change will be really helpful! Thank you!

**Comment by element4l** [comment]
I am in the same boat as the above user. The "Extra" field is frequently used including by other plugins, making it a terrible choice for displaying this information.

**Comment by eschnett** [comment]
@teristam This would be straightforward to do, probably a one-liner. I'll have a look.

**Comment by eschnett** [comment]
Done.
