### ISSUE TITLE
semantic scholar citations not retrieved

### ISSUE THREAD

**Issue by alainlhostis** [eschnett/zotero-citationcounts#9]
I have an entry (https://www.semanticscholar.org/paper/The-geography-of-advance-transit-oriented-in-Atkinson-Palombo-Kuby/1c672d754aa51e0a06f87cc20e9dc1907b309eb9) with 
- 78 citations in semanticscholar
- 52 citation in crossref

I can retrieve crossref citation count, but not semantischolar, I get a message saying "updating semanticscholar count updated 0 item"
This is just an example, I can retrieve NO semanticscholar citation count in my bibliography

**Comment by eschnett** [comment]
The web services providing citation counts have rate limiters. In many cases, you can only obtain a few citations per second. In some cases, your IP address might be blacklisted; if so, trying again the next day would help.

**Comment by alainlhostis** [comment]
thanks, will try later then
